name: ChangesetsDependencies
description: A GitHub action to automate Changesets creation based on dependencies changes in `package.json` files.
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  preCommit:
    description: "A script to run before committing the changesets files"
    required: false
branding:
  icon: "package"
  color: "blue"
